site_name: Posechain Engineering Portfolio
site_description: Engineering Portfolio
site_author: Jason Force
site_url: https://posechain.github.io/
copyright: ""

theme:
  name: material

  custom_dir: overrides
  logo: assets/images/posechain-logo.png
  favicon: assets/images/favicon.png
  palette:
    scheme: slate
    primary: blue grey
    accent: light blue
  features:
    - navigation.sections
    # - navigation.instant
    # - navigation.instant.progress
    # - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

extra_css:
  - assets/stylesheets/posechain.css
  - assets/stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  viewport: "width=device-width, initial-scale=0.85, maximum-scale=3, user-scalable=yes"  

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite

nav:
  - About Jason Force: index.md
  # - Selected Work: selected-work.md
  - Professional Materials:
      - Resume:
          - Space-Focused Resume: resume/space.md
          - Perception-Focused Resume: resume/perception.md
  - Contact: contact.md
  - Engineering Case Studies:
      - Dual-Mirror Optical Tracking:
          - Summary: work/dual-mirror-optical-tracking.md
          - Target Pointing Estimate: work/target-pointing-estimate.md
          - Coarse Pointing Estimate: work/coarse-pointing-estimate.md
          - Main Steering Mirror: work/main-steering-mirror.md
          - Camera Observation: work/camera-observation.md
          - ArUco Fiducial Detection: work/aruco-fiducial-detection.md
          - Image Plane Tracking Error: work/image-plane-tracking-error.md
          - Fast Steering Mirror: work/fast-steering-mirror.md
          - Fine Optical Stabilization: work/fine-optical-stabilization.md
      - Distributed Robotics:
          - Summary: work/distributed-robotics.md
      - Space Systems & Integration:
          - Summary: work/space-systems-payload-integration.md